### ISSUE TITLE
StackOverflowError when calling hashCode on mutually recursive schemas

### ISSUE THREAD

**Issue by cpchen** [everit-org/json-schema#302]

**Comment by tmarsteel** [comment]
Would it suffice to have `ReferenceSchema` not include the referred schema into the hashCode? Actually, that would make a lot of sense to me. The referred schema depends on the schema loader pretty much and the correctness of `ReferenceSchema`s equals+hashCode shouldn't depend on the schema loader.

**Comment by erosb** [comment]
Hello @tmarsteel , you can give it a go, but in that case I'm afraid the `equals()`will still run into an infinite recursion, so not sure if that helps a lot. Feel free to raise a PR with the fix and a passing test, if you want. Thanks for your idea anyway.

**Comment by rayokota** [comment]
We use this library in Confluent Schema Registry, and are seeing this error as well when `equals` or `hashCode` is called on a recursive schema.  https://github.com/confluentinc/schema-registry/issues/1549

**Comment by shionefaye** [comment]
@rayokota  [Conflunece Schema Registry](https://github.com/confluentinc/schema-registry/issues/1549) issue on recursive schema has been fixed and merged recently. What is needed to be done in this package?

**Comment by rayokota** [comment]
@shionefaye , the issue still exists in this library.  For Schema Registry the code has been changed to compare instances of `JsonNode` from Jackson rather than instances of `Schema` from this library.

**Comment by shionefaye** [comment]
> @shionefaye , the issue still exists in this library. For Schema Registry the code has been changed to compare instances of `JsonNode` from Jackson rather than instances of `Schema` from this library.

Got you. I misread your early message and thought this package depends on Conflunece Schema Registry.
