### ISSUE TITLE
JavaUtilRegexp does not implement equals

### ISSUE THREAD

**Issue by daniloarcidiacono** [everit-org/json-schema#340]
As per title, `JavaUtilRegexp` does not implement the `equals()` method.
Therefore, the following test fails:

```java
@Test
public void equalsWhyYouNoWork() {
    // { "type": "string", "pattern": "^\\d*$" }
    final String rawSchema = "{ \"type\": \"string\", \"pattern\": \"^\\\\d*$\" }";
    final JSONObject objectSchema = new JSONObject(new JSONTokener(rawSchema));

    final SchemaLoader loader = SchemaLoader.builder().schemaJson(objectSchema).draftV7Support().build();
    final Schema schema = loader.load().build();

    final SchemaLoader loader2 = SchemaLoader.builder().schemaJson(objectSchema).draftV7Support().build();
    final Schema schema2 = loader2.load().build();

    assertEquals(schema, schema2);
}
```

**Comment by erosb** [comment]
Thanks for reporting the problem. It is now fixed in commit `eb261ba8aa1a2137f7fd99a513fff3055a553db9` . In case you need the fix urgently, you can use it by setting the version number to the commit hash in your `pom.xml` (or whatevere you use).

**Comment by daniloarcidiacono** [comment]
I tried to use the new version, however the equality still does not work.

Explained here (https://stackoverflow.com/questions/10055034/java-comparing-two-pattern-objects), one should compare the pattern strings rather than the Pattern instances.

**Comment by erosb** [comment]
Hello @daniloarcidiacono , I released version `1.12.1` with a correct fix.

**Comment by daniloarcidiacono** [comment]
Awesome, thanks!
